# Generated by Django 3.2.8 on 2021-10-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=75)),
                ('st_addr', models.CharField(blank=True, max_length=75, null=True)),
                ('st_addr1', models.CharField(blank=True, max_length=75, null=True)),
                ('st_addr2', models.CharField(blank=True, max_length=75, null=True)),
                ('st_addr3', models.CharField(blank=True, max_length=75, null=True)),
                ('city', models.CharField(blank=True, max_length=75, null=True)),
                ('st', models.CharField(blank=True, max_length=2, null=True)),
                ('attn', models.CharField(blank=True, max_length=75, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
