# Generated by Django 3.2.8 on 2021-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='zip_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
