# Generated by Django 3.2.8 on 2021-10-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='st_addr',
            new_name='Street Address',
        ),
    ]
