# Generated by Django 3.2.8 on 2021-10-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_rename_st_addr_vendor_street address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('co_name',)},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Street Address',
            new_name='st_addr',
        ),
    ]
